pro/urls.py
from . import views
from django.urls import path

app_name='pro'
urlpatterns=[
    path('', views.IndexClassView.as_view(), name='index'),
    path('<int:pk>', views.FoodView.as_view(), name='detail'),
    path('add/', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:pk>', views.UpdateItem.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteItem.as_view(),name='delete'),
    path('product/', views.item_list, name='product')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from pro import views as pro_views

from rest_framework import routers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pro/', include('pro.urls')),

    path('register/', user_view.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('profile/', user_view.profilepage, name='profile'),

    # path('productlist/', pro_views.item_list, name='product')
]

router=routers.SimpleRouter()
router.register('product', user_view.ProViewSet)

urlpatterns += [
    path('', include(router.urls))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.name
    user_name=models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500, default='https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg')

    def get_absolute_url(self):
        return reverse('pro:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg', upload_to='profile_picture')
    location=models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

pro/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['name', 'item_price', 'item_desc', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=['username', 'email', 'password1', 'password2']

pro/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.core.paginator import Paginator

# Create your views here.

class IndexClassView(ListView):
    model = Item
    template_name = 'pro/index.html'
    context_object_name = 'item_list'

def item_list(request):
    item_objects=Item.objects.all()

    item_name=request.GET.get('item_name')
    if item_name != '' and item_name is not None:
        item_objects=item_objects.filter(name__icontains=item_name)

    paginator=Paginator(item_objects, 2)
    page=request.GET.get('page')
    item_objects=paginator.get_page(page)
    return render(request, 'pro/item_list.html', {'item_objects':item_objects})

class FoodView(DetailView):
    model = Item
    template_name = 'pro/detail.html'

class CreateItem(CreateView):
    model = Item
    fields = ['user_name','name', 'item_desc', 'item_price', 'item_image']
    template_name = 'pro/item_form.html'
    #
    # def form_valid(self, form):
    #     form.instance.user_name=self.request.user
    #
    #     return super().form_valid(form)

class UpdateItem(UpdateView):
    model = Item
    fields = ['user_name','name', 'item_desc', 'item_price', 'item_image']
    template_name = 'pro/item_form.html'

class DeleteItem(DeleteView):
    model = Item
    template_name = 'pro/item_delete.html'
    success_url = reverse_lazy('pro:index')

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm
from rest_framework import viewsets
from .models import Profile
from .serializers import UserSeri

# Create your views here.

def register(request):
    if request.method == 'POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, you are currently login')
            return redirect('login')
    else:
        form=RegisterForm()
    return render(request, 'user/register.html', {'form':form})

@login_required()
def profilepage(request):
    return render(request, 'user/profile.html')

class ProViewSet(viewsets.ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = UserSeri

pro/templates/pro/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
    <link rel="stylesheet" href="{% static 'pro/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'pro:index' %}" class="navbar-brand">Food App</a>
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'pro:create_item' %}">Add Item</a>
            <a class="nav-item nav-link" href="">Del Item</a>
            <a class="nav-item nav-link" href="">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

pro/templates/pro/detail.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}
{% extends 'pro/base.html' %}
{% block body %}
    <img src="{{ item.item_image }}" height="300px">
    {{ object.name }}
    {{ object.item_desc }}
    {{ object.item_price }}
    {{ object.user_name }}
    <a href="{%  url 'pro:update' object.pk%}">Update</a>
    <br>
    <a href="{% url 'pro:delete' object.pk %}">Delete</a>
{% endblock %}

pro/templates/pro/index.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}
{% extends 'pro/base.html' %}
{% block body %}
    <form action="" method="get">
        <input type="search" name="item_list">
        <button type="submit">Search</button>
    </form>

{% for item in  item_list %}
    <img src="{{ item.item_image }}" height="300px">
    {{ item.name }}
    <br>
    {{ item.item_desc }}
    <br>
    {{ item.item_price }}
    <br>
    {{ item.user_name }}
    <br>
    <a href="{%  url 'pro:detail' item.id%}">Details</a>
    <br>
{% endfor %}
{% endblock %}

pro/templates/pro/item_delete.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

<form method="post">
    {% csrf_token %}
    <h2>Are you sure to delete {{ object.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

pro/templates/pro/item_form.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}
{% extends 'pro/base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Add</button>
    </form>
{% endblock %}

pro/templates/pro/item_list.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

<form action="" method="get">
    <input type="search" name="item_name">
    <button type="submit">Search</button>
</form>

{% for item in item_objects %}
    {{ item.name }}
    <br>
{% endfor %}

{% if item_objects.has_previous %}
    <a href="?page=1">First</a>
    <a href="?page={{ item_objects.previous_page_number }}">Previous</a>
{% endif %}

Page: {{ item_objects.number }} of {{ item_objects.paginator.num_pages }}

{% if item_objects.has_next %}
    <a href="?page={{ item_objects.next_page_number }}">Next</a>
    <a href="?page={{ item_objects.paginator.num_pages }}">Last</a>
{% endif %}

users/templates/profile.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

users/templates/user/login.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

{% extends 'pro/base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

users/templates/user/logout.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

<h1>You have been log out</h1>

users/templates/user/profile.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

{{ user.username }}
<img src="{{ user.profile.image.url }}", height="100px">

users/templates/user/register.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

{% extends 'pro/base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Sign Up</button>
    </form>
{% endblock %}